

replicaCount: 1

image:
  repository: amagdi888/my-repo:hello-app

labels:
  app: web-app
  type: frontend

serviceAccount:
  enabled: false
  name: demo-sa

service:
  protocol: TCP
  type: ClusterIP 
  port: 8000
  labels:
    name: webapp-service

deployment:
  port: 8000

ingress:
  class: alb
  host: testwebapp.vijays.controller.gorafay.net
