apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-deployment
  labels:
    {{- include "webapp-chart.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      {{- include "webapp-chart.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "webapp-chart.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: {{ .Release.Name}}
        image: {{ .Values.image.repository}}
        ports:
        - containerPort: {{ .Values.deployment.port}}
        command:
        - sleep
        - "600"
