User:
  name: Vijay

replicaCount: 1

image:
  repository: nginx:latest 

labels:
  app: web-app
  type: frontend

serviceAccount:
  enabled: false
  name: demo-sa

service:
  protocol: TCP
  type: ClusterIP 
  port: 80
  labels:
    name: webapp-service

deployment:
  port: 80
