apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    name: {{ .Values.service.labels.name}}
spec:
{{- with .Values.service }}
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      protocol: {{ .protocol}}
{{- end }}
  selector: 
    {{- include "webapp-chart.service.labels" . | indent 4 -}}
    
