

replicaCount: 1

image:
  repository: amagdi888/my-repo:hello-app 

pod:
  labels:
    app: web-app
    type: frontend

serviceAccount:
  enabled: true
  name: demo-sa

service:
  protocol: TCP
  type: ClusterIP 
  port: 8000
  labels:
    app: web-app
    type: frontend    
deployment:
  port: 8000

ingress:
  class: alb
  host: testwebapp.vijays.controller.gorafay.net
