User:
  name: Vijay

replicaCount: 1

image:
  repository: nginx:latest

labels:
  app: web-app
  type: frontend

serviceAccount:
  enabled: true
  name: demo-sa

service:
  protocol: TCP
  type: ClusterIP
  port: 80
  labels:
    name: webapp-service

deployment:
  port: 80

ingress:
  class: alb
  # must update hostname. Pick any name in the domain vijays.controller.gorafay.net
  host: webapp.vijays.controller.gorafay.net
